out_dir: results
metric_best: accuracy
wandb:
  use: True
  project: TUDatasets
dataset:
  format: PyG-TUDataset
  task: graph
  task_type: classification_multilabel
  split_mode: random
  split: [0.8, 0.1, 0.1]
  transductive: False
  repeat: 50
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: dynamic_gnn
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 1
  dim_inner: 64
  layer_type: gcnconv
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
dynamic:
  num_snapshots: 1 
  pre_transform: "fosr" 
  aggregation: "sum"
  num_iterations: 40
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 100
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5